hello world

In [ ]:
print(3+5)

8


In [ ]:
print("3"+"5")

35


In [ ]:
x = 5

In [ ]:
type(x)

int

In [ ]:
y = "Hello"

In [ ]:
type(y)

str

In [ ]:
lst1 = [1, 3.14, "Hi", True, None]

In [ ]:
lst1

[1, 3.14, 'Hi', True, None]

In [ ]:
type(lst1)

list

In [ ]:
len(lst1) # I am a comment

5

### What is Data Exploration?

1.  **Initial Investigation:** Data exploration is the first step in data analysis, involving an open-minded examination of a dataset to understand its main characteristics.
2.  **Discovery of Patterns:** It focuses on discovering patterns, anomalies, relationships, and trends in the data, often before formal modeling or hypothesis testing.
3.  **Visualization and Statistics:** It heavily relies on data visualization techniques (e.g., histograms, scatter plots) and descriptive statistics (e.g., mean, median, standard deviation) to summarize and illustrate data properties.
4.  **Hypothesis Generation:** The insights gained during exploration help in formulating hypotheses, identifying important variables, and guiding subsequent analytical steps.
5.  **Data Quality Assessment:** It also helps in identifying data quality issues such as missing values, outliers, or inconsistencies, which need to be addressed in later stages.

In [ ]:
import numpy as np

In [ ]:
votes = np.array([775, 880, 900, 1107, 1378])
costs = np.array(["1000", "1100", "500", "1300", "1500"])

In [ ]:
type(votes)

numpy.ndarray

In [ ]:
lst1

[1, 3.14, 'Hi', True, None]

In [ ]:
lst1 * 2

[1, 3.14, 'Hi', True, None, 1, 3.14, 'Hi', True, None]

In [ ]:
votes * 2

array([1550, 1760, 1800, 2214, 2756])

In [ ]:
votes.shape # (rows, columns)

(5,)

In [ ]:
votes.ndim # dimension of numpy array

1

In [ ]:
votes.size # total elements

5

In [ ]:
two_d_data = np.array([
    votes,
    costs
])

In [ ]:
two_d_data

array([['775', '880', '900', '1107', '1378'],
       ['1000', '1100', '500', '1300', '1500']], dtype='<U21')

In [ ]:
two_d_data.shape

(2, 5)

In [ ]:
cost_int = costs.astype(int)

In [ ]:
cost_int

array([1000, 1100,  500, 1300, 1500])

In [ ]:
costs

array(['1000', '1100', '500', '1300', '1500'], dtype='<U4')

In [ ]:
cost_str = costs.astype(str)
cost_str

array(['1000', '1100', '500', '1300', '1500'], dtype='<U4')

In [ ]:
a = np.array(["abc", "xyz"])
a.astype(int)

ValueError: invalid literal for int() with base 10: np.str_('abc')

In [ ]:
b = np.array([100.9, 107.1])
b.astype(int)

array([100, 107])

In [ ]:
b

array([100.9, 107.1])

Indexing - Accessing a single element using its position

In [ ]:
votes

array([ 775,  880,  900, 1107, 1378])

In [ ]:
votes[1]

np.int64(880)

In [ ]:
votes[-4]

np.int64(880)

In [ ]:
votes[-1]

np.int64(1378)

Slicing - accessing a slice or small part of an array

In [ ]:
votes

array([ 775,  880,  900, 1107, 1378])

In [ ]:
votes[1:3]

array([880, 900])

In [ ]:
votes[:4]

array([ 775,  880,  900, 1107])

In [ ]:
votes[:4:2]

array([775, 900])

In [ ]:
votes[::2]

array([ 775,  900, 1378])

In [ ]:
two_d_data

array([['775', '880', '900', '1107', '1378'],
       ['1000', '1100', '500', '1300', '1500']], dtype='<U21')

In [ ]:
two_d_data.shape # (2, 5)

(2, 5)

In [ ]:
two_d_data[:1, 1:4]

array([['880', '900', '1107']], dtype='<U21')

In [ ]:
two_d_data[:, 0]

array(['775', '1000'], dtype='<U21')

In [ ]:
two_d_data[:, 0].shape

(2,)

In [ ]:
#In a (m,n) array, what shape is returned by arr[:,0]

#In a (2, 5) array, what shape is returned by arr[:, 0] --> (m, )

In [ ]:
votes[:]

array([ 775,  880,  900, 1107, 1378])